version: "3"

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./www:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
